//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepMotorControllerUIPart.SettingsFolder {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class DiaphragmsStn : global::System.Configuration.ApplicationSettingsBase {
        
        private static DiaphragmsStn defaultInstance = ((DiaphragmsStn)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DiaphragmsStn())));
        
        public static DiaphragmsStn Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.053")]
        public float D1 {
            get {
                return ((float)(this["D1"]));
            }
            set {
                this["D1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.053")]
        public float D2 {
            get {
                return ((float)(this["D2"]));
            }
            set {
                this["D2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.095")]
        public float D3 {
            get {
                return ((float)(this["D3"]));
            }
            set {
                this["D3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.095")]
        public float D4 {
            get {
                return ((float)(this["D4"]));
            }
            set {
                this["D4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D5 {
            get {
                return ((float)(this["D5"]));
            }
            set {
                this["D5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D6 {
            get {
                return ((float)(this["D6"]));
            }
            set {
                this["D6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D7 {
            get {
                return ((float)(this["D7"]));
            }
            set {
                this["D7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D8 {
            get {
                return ((float)(this["D8"]));
            }
            set {
                this["D8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D9 {
            get {
                return ((float)(this["D9"]));
            }
            set {
                this["D9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D10 {
            get {
                return ((float)(this["D10"]));
            }
            set {
                this["D10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D11 {
            get {
                return ((float)(this["D11"]));
            }
            set {
                this["D11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D12 {
            get {
                return ((float)(this["D12"]));
            }
            set {
                this["D12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D13 {
            get {
                return ((float)(this["D13"]));
            }
            set {
                this["D13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D14 {
            get {
                return ((float)(this["D14"]));
            }
            set {
                this["D14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D15 {
            get {
                return ((float)(this["D15"]));
            }
            set {
                this["D15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D16 {
            get {
                return ((float)(this["D16"]));
            }
            set {
                this["D16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D17 {
            get {
                return ((float)(this["D17"]));
            }
            set {
                this["D17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D18 {
            get {
                return ((float)(this["D18"]));
            }
            set {
                this["D18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D19 {
            get {
                return ((float)(this["D19"]));
            }
            set {
                this["D19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.188")]
        public float D20 {
            get {
                return ((float)(this["D20"]));
            }
            set {
                this["D20"] = value;
            }


        }

        public float[] GetPropertiesArray()
        {
            var properties = new float[Properties.Count];

            return properties;
        }
    }
}
